version: "3.9"

services:  
  dotnetlab02:
    
    # Go to dockerhub and find the image for dotnet sdk 6.0
    image: "<finn container på dockerhub>"
    container_name: minimalapi60

    tty: true
    
    
    # Configuration options that are applied at build time.    
    #ports:
    #  - 3000:80
        
    # Set environment variables
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=compose
    
    # Mount host directories to container directories
    volumes:
      - ./source:/source
      # Blokker binærkataloger (her må du fikse litt selv)
      - obj-volume:/minimalapi/obj
      - bin-volume:/minimalapi/bin
      #Blokker NPM katalogen ut av containeren enten sånn
      # - npm-volume:/source/minimalapi/obj
      #eller sånn, hva blir forskjellen??
      # - "/source/minimalapi/obj"

volumes:
  obj-volume:
  bin-volume: