version: "3.9"

services:
  freepasca01:
    # Specify the image to start the container from
    #image: freepascal/fpc:3.2.0-full
    image: primeimages/freepascal
    container_name: freepascal01
    tty: true

    # Expose ports (HOST:CONTAINER)
    ports:
      - 9080:9080

    # Set environment variables
    #environment:

    # Mount host directories to container directories
    volumes:
      - ./source:/source
      #- npm-volume:/source/docktest/node_modules

#volumes:
#  npm-volume:
