version: "3.9"

services:  
  dotnetlab01:
    
    # Go to dockerhub and find the image for dotnet sdk 6.0
    image: "mcr.microsoft.com/dotnet/sdk:6.0"
    container_name: minimalapi60

    tty: true

    #remoteUser: magnea
    
    # Configuration options that are applied at build time.    
    ports:
      - 3000:80
      - 3001:443
    
    # Set environment variables
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=compose
    
    # Mount host directories to container directories
    volumes:
      - ./source:/source
      - obj-volume:/minimalapi/obj
      - bin-volume:/minimalapi/bin

volumes:
  obj-volume:
  bin-volume: