version: "3.9"

services:  
  dotnetlab01:
    
    # Go to dockerhub and find the image for dotnet sdk 6.0
    image: "mcr.microsoft.com/dotnet/sdk:6.0"
    container_name: minimalapi60

    tty: true

    #remoteUser: magnea
    
    # Configuration options that are applied at build time.    
    ports:
      - 3000:5059
      - 3001:7212
    
    # Set environment variables
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_RUNNING_IN_CONTAINER=compose
    
    # Mount host directories to container directories
    volumes:
      - ./source:/source
      # Vegas prinsippet på binærkatalog
      - '/source/MinApi/obj'
      - '/source/MinApi/bin'
      # Eller lagre filer i egne persistente volumer?
      #- obj-volume:/source/MinApi/obj
      #- bin-volume:/source/MinApi/bin

#volumes:
#  obj-volume:
#  bin-volume: