version: "3.9"

services:  
  dotnetlab01:
    
    # Go to dockerhub and find the image for dotnet sdk 6.0
    image: "swift:5.1"
    container_name: swiftdockerlab

    tty: true

    #remoteUser: magnea
    
    # Configuration options that are applied at build time.    
    #ports:
    #  - 3000:80
    #  - 3001:443
    
    # Set environment variables
    #environment:
    #  - ASPNETCORE_ENVIRONMENT=Development
    #  - DOTNET_RUNNING_IN_CONTAINER=compose
    
    # Mount host directories to container directories
    volumes:
      - ./source:/source
    