version: "3.9"

services:  
  rustlab01:
    
    # Go to dockerhub and find the image for dotnet sdk 6.0
    image: rust:1.63-buster
    container_name: rustlab01

    tty: true
        
    # Mount host directories to container directories
    volumes:
      - './source:/source'
      - '/source/target'

