version: "3.9"

services:
  prolog01:  
    # Specify the image to start the container from       
    build:
      context: .
      dockerfile: Dockerfile

    container_name: swiprolog01
    tty: true

    # Mount host directories to container directories
    volumes:
      - ./source:/source

    # Expose ports (HOST:CONTAINER)
    ports:
      - 8095:8080